DROP DATABASE IF EXISTS bamazon_DB;
CREATE DATABASE bamazon_DB;
USE bamazon_DB;
CREATE TABLE inventory(
   id INT NOT NULL AUTO_INCREMENT,
   item VARCHAR(100) NOT NULL,
   price DECIMAL(10,2) NOT NULL,
   stock INT DEFAULT 0,
   PRIMARY KEY (id)
);